-- MySQL Script generated by MySQL Workbench
-- Fri 13 Apr 2018 12:53:22 AM CEST 
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Author: Naumce Ivanovski

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pxl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pxl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pxl` DEFAULT CHARACTER SET latin1 ;
USE `pxl` ;

-- -----------------------------------------------------
-- Table `pxl`.`pxl`
-- UNIQUE INDEX WILL BE USED FOR INSERT IGNORE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pxl`.`pxl` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT(5) NULL,
  `day` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `year_UNIQUE` (`year` ASC, `day` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
